### ISSUE TITLE
Test make_goal with movebase simulation

### ISSUE THREAD

**Issue by andreseg9726** [umigv/atlas#245]
Last week we finally got something useful from the simulation! This is exciting since we can use it to test what we build. I would like you to test and report the behavior of your make goal node on the simulation. Go to http://atlas.umigv.com/controls to see how to start movebase and the simulation. The only thing you would have to do differently is, instead of using Rviz to send goals to the robot, run your node and see if the robot receives the goal.

This ticket will be closed once we can get the node to tell our robot where to go.

**Comment by atish3** [comment]
The w variable doesn't control the yaw of the robot. What we would have to do is convert to RPY coordinates. We're going to have to change the code so that the variables we're passing in/working with actually control the parameters we want to control. I'll work a bit on this today, but this may spill over into next week.

I have managed to run the make_goal code we have on GitHub. The robot doesn't do anything in simulation, and I can't tell if its even receiving the output from make_goal.
