### ISSUE TITLE
Put all sliders on frame

### ISSUE THREAD

**Issue by yomn61** [umigv/atlas#77]
-The 8-20 sliders need to be in the correct locations for the mounting of acrylic plates, pillow blocks, and gearboxes

**Comment by austone** [comment]
Looks like you may have forgotten to put sliders on the inside longitudinal rails.

**Comment by arnwill** [comment]
I really hope not but it is definitely possible. I’d have to see it in person to know for sure but The other possibility is that the rails were not flush and someone moved the frame. We ran into that problem while building it. Since the sliders aren’t connected to anything, if the rails are not flush and the frame is tilted the sliders can sometimes manage to fall out. If any additional sliders need to be added I can take care of it on Sunday… but the sooner we can connect gear boxes and pillow blocks to the sliders the better off we will be.

Sincerely,

Will Arnold

**Comment by austone** [comment]
In my experience, it is a bit easier to add sliders to a part then install it than it is to screw into the t-nuts through the part. It'll work out either way
